### ISSUE TITLE
Basic Road Laying UI

### ISSUE THREAD

**Issue by aeickhoff** [citybound/citybound#6]
- [x] Road Rendering #2 
- [x] Basic UI #13
- [x] Draw and adapt a single road stroke
- [x] Add several road strokes
- [x] Create "cut" road strokes and intersection areas
- [x] Create connecting road strokes on intersections
- [x] Basic Plan realisation
- [x] Interaction with existing roads & more complete Plan realisation
- [x] Moving existing roads
- [x] Curved strokes and node direction
- [x] Dual-side roads
- [x] Multilane strokes
- [x] Correct overlaps on intersections
- [x] Transfer lanes & overlaps on parallel lanes
- [x] Make multilane roads look better #12
- [x] Fix non-straight intersections
- [x] Fix realization of transfer lanes
- [x] Fix intersection overlaps
- [x] Fix disconnected continued transfer lanes
- [x] T-Intersections
- [x] Allow deletion of roads #20
- [x] UI for modifying multilane strokes #20
- [x] Intersection traffic light timing
- [x] Live preview of plan changes #20
- [x] Reimplement continuation of roads
- [x] Implement adding of lanes #20
- [x] Implement connection of roads
- [x] Cancel/Undo/Redo
- [x] Self-connection of roads
- [x] Quickly set number of lanes with number keys
- [x] Self-intersection of strokes
- [ ] Smarter connection of roads with proper biarc connectors
